enableImmutableInstalls: false
nodeLinker: node-modules
enableGlobalCache: false
nmMode: hardlinks-local
npmRegistryServer: 'https://registry.npmjs.org/'
cacheFolder: '.yarn/cache'
enableMirror: true
globalFolder: '.yarn/global'
npmAlwaysAuth: false
npmScopes:
  default:
    npmAlwaysAuth: false
